apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: node-docker
spec:
  type: state.redis
  version: v1
  metadata:
  - name: keyPrefix
    value: none
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
